### ISSUE TITLE
[RFC] Search Settings

### ISSUE THREAD

**Issue by itsnoa04** [strapi-community/strapi-plugin-search#4]
# [RFC] Search Settings

# Intro
The Objective of this RFC is to provide a high level overview of the `Search Settings` tab and to fully flush out the  `Search Settings` implementation.

Any feedback is welcome and appreciated.

# Search Analytics Tab

## Overview

The `Search Settings` tab will be a custom tab in the strapi admin panel to monitor search indexing ( Document CRUD Activities ) and to provide admin management tools for developers and non-technical users.

### Content-Type Indexing Overview

The `Search Settings` tab will provide a high level overview of the search index. This will include the following information:

- Total Documents Indexed ( Count ) of each Content-Type
- List of Content-Types that are indexed
- List of Indexes( Collections ) used
- List of Engines used

### Global Audit Log

The `Search Settings` tab will provide a global audit log of all search indexing activities. This will include CRUD operations for each document indexed in every index.

### Engine Audit Log

The `Search Settings` tab will provide an engine audit log of all search indexing activities. This will include CRUD operations for each document indexed in a specific engine.

### Content-Type Audit Log

The `Search Settings` tab will provide a Content-Type audit log of all search indexing activities. This will include CRUD operations for each document indexed in a specific Content-Type.

### Engine Management

The `Search Settings` tab will provide a management interface for developers and non-technical users to manage the search engine. This will include the following features:

- List Available Engines
- Re-Index All Content-Types mapped to a specific Engine

Further activities regarding `Engine` must be performed in the plugin configuration.

### Index Management

The `Search Settings` tab will provide a management interface for developers and non-technical users to manage the search index. This will include the following features:

- Re-Index Content-Type ( Single )
- Re-Index All Content-Types mapped to a specific Index

Further activities regarding `Index` must be performed in the plugin configuration.

### Analytics Tab
![image](https://github.com/strapi-community/strapi-plugin-search/assets/70159114/b707c74e-b921-491b-b333-dff35a23dac2)

### Tools Tab
![image](https://github.com/strapi-community/strapi-plugin-search/assets/70159114/e5c6631c-53ff-4ddf-a984-e0ca3bcf47ea)

## Note

This RFC is a work in progress and will be updated as the project progresses.

Not all features listed in this RFC will be available in the initial release (v1).

**Comment by ComfortablyCoding** [comment]
Overall this looks great!

My questions/feedback are as follows:
1. We should seperate tools and analtyics to seperate sub menus under a `Search Plugin` heading. This will make it inline with the format for other settings in the settings menu.
![image](https://github.com/strapi-community/strapi-plugin-search/assets/44623501/8d81cc5c-ae13-4f05-ad76-ce8cd602f8e6)
2. Instead of doing 3 seperate views for audit logs we should have a 3rd sub menu  for `Audit Logs` that contains a filterable table of all logs. As its a content type data view we should probably replicate the same view as the ones in `Content Manager` for content types. This will allow them to filter/search on whatever conditions they might want. It will also be less maintenance on our side (I hope) as everything is in one place.
3. Should `Index Management` also provider a list of used indexes?
4. As an index can contain multiple content types should we also provide a `Content Type Management`? Similar to engine and index it will provide management for indexed content types. If so we should move the `Re-Index Content-Type (Single)` to here instead and add list of indexed content types. This will seperate all 3 paradigms nicely.
5. `Overview` might be more appropriate than `Management`.
6. What is the flow for accessing these management interfaces?

I think any more than this should wait for user feedback once released.

**Comment by itsnoa04** [comment]
Yes to all

**Comment by itsnoa04** [comment]
Closing this RFC in favour of #6 and #7
